[package]
name = "ec_sac_beta"
version = "0.1.1"
edition = "2018"
publish = false

[[bin]]
name = "sac"
test = false
bench = false

[dependencies]
#rocket = { path = "../../core/lib" }
rocket = "0.4.10"
