[package]
name = "sac"
version = "0.1.1"
edition = "2018"
publish = false

#deprecated
#[dependencies]
#rocket = { path = "../../core/lib" }
#rocket = "0.4.10"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
